before_cache:           #to avoid uploading cache every time we build
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/backend/.gradle/caches/
    - $HOME/backend/.gradle/wrapper/
    - $HOME/frontend/node_modules
env:
  - DB=orientDB
before_install:
  - cd backend
  - chmod +x gradlew    #to avoid "/home/travis/.travis/functions: line 315: ./gradlew: Permission denied" error

matrix:
  fast_finish: true
  include:
    - node_js:
      env: TO_TEST=FRONTEND
    - java:
      env: TO_TEST=BACKEND

install:
  - |
    if [ "$TO_TEST" == "FRONTEND" ]; then
      cd frontend
      npm install
      fi

script:
  - |
    if [ "$TO_TEST" = "BACKEND" ];
      cd $HOME/backend/
      ./gradlew assemble
      ./gradlew check
      fi
  - |
    if [ "$TO_TEST" = "FRONTEND" ]; then
      npm start
      npm test
      fi