before_cache:           #to avoid uploading cache every time we build
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/backend/.gradle/caches/
    - $HOME/backend/.gradle/wrapper/
    - $HOME/frontend/node_modules
env:
  - DB=orientDB


matrix:
  fast_finish: true
  include:
    - language: node_js
    - language: java

script:
  - if [ $language == "java" ]; then
      cd backend;
      chmod +x gradlew;
      ./gradlew assemble;
      ./gradlew check;
      fi
  - if [ $language == "node_js" ]; then
      cd frontend;
      npm run build;
      npm test;
      fi