before_cache:           #to avoid uploading cache every time we build
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/backend/.gradle/caches/
    - $HOME/backend/.gradle/wrapper/
    - $HOME/frontend/node_modules
env:
  - DB=orientDB
before_install:
  -

matrix:
  fast_finish: true
  include:
    - node_js:
      env: TO_TEST=FRONTEND
    - java:
      env: TO_TEST=BACKEND

install:
  - if [ $TO_TEST == "FRONTEND" ]; then
      cd frontend;
      npm install;
      cd ..;
      fi

script:
  - if [ $TO_TEST == "BACKEND" ]; then
      cd backend;
      chmod +x gradlew;
      ./gradlew assemble;
      ./gradlew check;
      fi
  - if [ $TO_TEST == "FRONTEND" ]; then
      cd frontend;
      npm start;
      npm test;
      fi