insert into HelloIOBagiety values (1, 'Bagieta 1');
insert into HelloIOBagiety values (2, 'Bagieta 2');
insert into HelloIOBagiety values (3, 'Bagieta 3');
insert into HelloIOBagiety values (4, 'Bagieta 4');
 insert into App_User values (1, null, 'systemwbudowany@gmail.com', null, 'Jan', null, 'Kowalski', 1);
 insert into Students_Group values (1, 1, 'computer science', 'group 1', '3');
 insert into Classroom values (1, 'D-17', 1, '3.17');
 insert into Subject values(1, 'WDI');
 insert into Lesson values (1, to_date('17/12/2015', 'DD/MM/YYYY'), '12:45', 1, 'meeting1', '11:15', 1,1,1,1);
 insert into Lesson values (2, to_date('17/12/2015', 'DD/MM/YYYY'), '14:45', 1, 'meeting1', '13:15', 1,1,1,1);